# Generated by Django 4.0.1 on 2024-03-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=5)),
                ('payment_status', models.CharField(max_length=15)),
                ('transaction_id', models.CharField(max_length=5)),
                ('shipment_status', models.CharField(max_length=20)),
            ],
        ),
    ]
